---
title: "AnaliseCEAP"
author: "Adbys Vasconcelos"
date: "06/11/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
library(tidyr)
library(sqldf)

gastos <- read.csv("dadosCEAP.csv")


gastos$valorGlosa <- as.numeric(sub(",", ".", gastos$valorGlosa, fixed = TRUE))

formaDeUsoPorCategoria <- gastos %>% group_by(TipoDespesa = tipoDespesa) %>% filter(sgUF == "PB", valorDocumento > 0, valorLíquido > 0) 

gastoPorEstado <- gastos %>% group_by(Estado = sgUF) %>% filter(Estado != "NA", valorDocumento > 0, valorLíquido > 0) %>% summarise(Gastos = sum(valorLíquido)) %>% arrange(Gastos)


totalGasto <- gastos %>% filter(sgUF != "NA", valorDocumento > 0, valorLíquido > 0) %>% summarise(GastoTotal = sum(valorLíquido))


gastosPorRegiao <- gastos %>%  filter(sgUF != "NA", valorDocumento > 0, valorLíquido > 0) %>% mutate(Regiao = ifelse(sgUF == 'PB' | sgUF == 'PE' | sgUF == 'RN' | sgUF == 'CE' | sgUF == 'PI' | sgUF == 'BA' | sgUF == 'MA' | sgUF == 'SE' | sgUF == 'AL', 'NE', ifelse(sgUF == 'ES' | sgUF == 'RJ' | sgUF == 'MG' | sgUF == 'SP', 'SE', ifelse(sgUF == 'RS' | sgUF == 'PR' | sgUF == 'SC', 'S', ifelse(sgUF == 'MS' | sgUF == 'GO' | sgUF == 'MT' | sgUF == 'DF', 'CO', ifelse(sgUF == 'RO' | sgUF == 'AC' | sgUF == 'PA' | sgUF == 'AM' | sgUF == 'RR' | sgUF == 'AP' | sgUF == 'TO', 'N', 'NA')))))) %>% group_by(Regiao) %>% summarise(Gastos = (sum(valorLíquido)/totalGasto$GastoTotal) * 100) %>%  arrange(Gastos)
                                   

regiaolbls <- gastosPorRegiao$Regiao
regiaolbls <- paste(lbls, round(gastosPorRegiao$Gastos, 2))
regiaolbls <- paste(lbls,"%",sep="")

pie(gastosPorRegiao$Gastos, labels = regiaolbls, main = "Percentual de gastos da CEAP por região")




ggplot(formaDeUsoPorCategoria, aes(x = "", y = valorLíquido, fill=TipoDespesa)) + geom_boxplot()+  labs(title = "Distribuição dos gastos da CEAP no Estado da Paraíba", x = "Tipo de Gasto", y = "Gasto(R$)") + coord_cartesian(ylim = c(0, 30000)) + theme(legend.text = element_text(size=6))


```
```{r}

totalGastoParaiba <- gastos %>% filter(sgUF == "PB", valorDocumento > 0, valorLíquido > 0) %>% summarise(GastoTotal = sum(valorLíquido))

porcentagemGastaPorParlamentar <- gastos %>% group_by(Parlamentar = nomeParlamentar) %>% filter(sgUF == "PB", valorDocumento > 0, valorLíquido > 0) %>% summarise(Gastos = ((sum(valorLíquido)/totalGastoParaiba$GastoTotal)) * 100) %>% arrange(Gastos)

lbls <- tail(porcentagemGastaPorParlamentar$Parlamentar, n=14)
lbls <- paste(lbls, round(tail(porcentagemGastaPorParlamentar$Gastos, n=14), 2))
lbls <- paste(lbls,"%",sep="")

pie(tail(porcentagemGastaPorParlamentar$Gastos, n=14), labels = lbls, cex=0.7)


```

